name: weather
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  
  # Iconos e Interfaz
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  cached_network_image: ^3.4.1
  
  # Autenticación y Persistencia
  google_sign_in: ^7.2.0
  flutter_secure_storage: ^10.3.1
  shared_preferences: ^2.5.5
  
  # Geolocalización y Mapas
  geolocator: ^14.0.3
  google_maps_flutter: ^2.5.3
  flutter_map: ^8.3.1
  latlong2: ^0.10.1
  
  # Consumo de API
  http: ^1.2.1
  dio: ^5.9.2
  pretty_dio_logger: ^1.4.0
  
  # Manejo de Estado y Utilidades
  provider: ^6.1.5+1
  logger: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true